#!/bin/sh
set -e; set -u

# License = MIT
# Author = https://gitlab.com/almr/
# Homepage = https://gitlab.com/almr/apt-upgrade-cli/

# https://unix.stackexchange.com/questions/603514/apt-upgrade-package-without-marking-as-manually-installed

# TODO: apt options

DEFSTATUS=off
while test $# -gt 0; do
  case "$1" in
    --all) DEFSTATUS=on; shift ;;
    --help) printf "Args: [-u|--update] [--all] [pkg ...]\n"; exit 0 ;;
    -u|--update) apt update; shift ;;
    *) break ;;
  esac
done

sel_pkgs () (
  US=$(apt list --upgradeable 2>/dev/null | grep '/.*upgradable' | cut -f1 -d /)  # apt is not scriptable by its own confession; format: zsh/focal 5.8-3ubuntu1 i386
  test -z "$US" && return
  for u in $US; do set -- "$@" "$u" '' "$DEFSTATUS"; done
  dialog --stdout --separate-output --checklist 'Upgrade' -1 -1 -1 "$@"
)

test $# -eq 0 && set -- $(sel_pkgs)
test $# -eq 0 && exit

AUTOS=$(apt-mark showauto "$@")
apt install --no-install-recommends "$@"
test -n "$AUTOS" && apt-mark auto $AUTOS >/dev/null
