#!/bin/bash -eu

# License = MIT
# Author = https://gitlab.com/almr/
# Homepage = https://gitlab.com/almr/apt-upgrade-cli/

# https://unix.stackexchange.com/questions/603514/apt-upgrade-package-without-marking-as-manually-installed

# TODO: apt options

DEFSTATUS=off
BACKEND=dialog
while test $# -gt 0; do
  case "$1" in
    --all|-a) shift; DEFSTATUS=on ;;
    --help|-h) printf "Args: [-u|--update] [--all] [--editor|-e] [pkg ...]\n"; exit 0 ;;
    --update|-u) shift; apt update ;;
    --editor|-e) shift; BACKEND=edit ;;
    --) shift; break ;;
    -*) echo "Unknown: $1"; exit 1 ;;
    *) break ;;
  esac
done


UPGPCRE='^([^/]+)/.*\bupgradable '  # apt isn't scriptable by its own confession; format: linux-doc/focal-updates 5.4.0-59.65 all [upgradable from: 5.4.0-58.64]

upgable2pkgs () {
  perl -wlnE 'print $1 if m@'"$UPGPCRE"'@'
}

dialog_sel_pkgs () (
  US=$(upgable2pkgs)
  test -z "$US" && exit 0
  for u in $US; do set -- "$@" "$u" '' "$DEFSTATUS"; done
  dialog --stdout --separate-output --checklist 'Upgrade' 0 0 0 "$@" 0<&5 1>&6  # though dialog seems to figure out the tty by itself
)

edit_sel_pkgs () (
  USF=$(mktemp)
  trap 'rm -f "$USF"' EXIT
  if test "off" = "$DEFSTATUS"; then pfx='#'; else pfx=' '; fi
  sed -e "s/^/$pfx/" >"$USF"
  test -s "$USF" || exit 0
  $EDITOR "$USF" 0<&5 1>&6
  grep -v '^#' "$USF" | upgable2pkgs
)

sel_pkgs () {
  apt list --upgradeable "$@" 2>/dev/null | grep -P "$UPGPCRE" |
    ${BACKEND}_sel_pkgs
}

exec 5<&0 6>&1

set -- $(sel_pkgs "$@")
test $# -eq 0 && { echo 'No upgrades available' 1>&2; exit; }

AUTOS=$(apt-mark showauto "$@")
clear
(set -x; apt install --no-install-recommends "$@")
test -n "$AUTOS" && apt-mark auto $AUTOS >/dev/null
