#!/bin/bash
set -eu

# License = MIT
# Author = https://gitlab.com/almr/
# Homepage = https://gitlab.com/almr/apt-upgrade-cli/

# https://unix.stackexchange.com/questions/603514/apt-upgrade-package-without-marking-as-manually-installed

# TODO: apt options

_G_apt_conf=

usage () {
  printf '%s\n' 'Args: [-u|--update] [--all] [--editor|-e] [-o APT_KEY=VAL ..] [pkg ..]'
  exit 0
}
parse_args () {
DEFSTATUS=off
BACKEND=edit
OREC='-o APT::Install-Recommends=0'
UPGPCRE='^([^/]+)/.*\bupgradable '  # apt isn't scriptable by its own confession; format: linux-doc/focal-updates 5.4.0-59.65 all [upgradable from: 5.4.0-58.64]
while test "$#" != 0; do
  local arg; arg=$1; shift
  case "$arg" in
    --) break ;;
    -h|--help) usage; exit 0 ;;
    -v|--verbose) set -x ;;
    --all|-a) DEFSTATUS=on ;;
    --update|-u) apt update ;;
    --editor|-e) BACKEND=edit ;;
    --dialog) BACKEND=dialog ;;
    --rec|--with-install-recommends) OREC='-o APT::Install-Recommends=1' ;;
    -o) _G_apt_conf="$_G_apt_conf -o $1"; shift ;;
    -t) arg=$1; shift; set -- -o "APT::Default-Release=$arg" "$@" ;;
    -*) echo "Unknown: $arg"; exit 1 ;;
    *) set -- "$arg" "$@"; break ;;
  esac
done
ARGV=( "$@" )
}

upgable2pkgs () {
  sed -Ene 's@.*'"$UPGPCRE"'.*@\1@p'
}

dialog_sel_pkgs () (
  US=$(upgable2pkgs)
  test -z "$US" && exit 0
  for u in $US; do set -- "$@" "$u" '' "$DEFSTATUS"; done
  # 2>&1 to captured stdout (dialog defaults to --stderr); then restore tty stdin/out
  # simpler to use --stdout so dialog reopens the tty (but docs warn against)
  dialog --separate-output --checklist 'Upgrade' 0 0 0 "$@" 2>&1 0<&5 1>&6
)

__set_editor_env () {  # set $EDITOR to app-preferred, or existing $EDITOR, or detected
  EDITOR=${APTUP_EDITOR:-${EDITOR:-$(which sensible-editor || which nano || which editor || which vim || which vi)}}
}
edit_sel_pkgs () (
  USF=$(mktemp)
  trap 'rm -f "$USF"' EXIT  # bashism
  if test 'off' = "$DEFSTATUS"; then pfx='#'; else pfx=' '; fi
  sed -e "s/^/$pfx/" >"$USF"
  test -s "$USF" || exit 0
  __set_editor_env; $EDITOR "$USF" 0<&5 1>&6  # though we're on Debian for sure
  grep -v '^#' "$USF" | upgable2pkgs
)

sel_pkgs () {
  [[ $- = *x* ]] || echo 1>&2 'Running apt list --upgradeable ...'
  apt list --upgradeable $OREC $_G_apt_conf "$@" 2>/dev/null | grep -P "$UPGPCRE" |
    ${BACKEND}_sel_pkgs
}

exec 5<&0 6>&1

parse_args "$@"; set -- "${ARGV[@]}"
set -- $(sel_pkgs "$@")
test $# -eq 0 && { echo 'No upgrades available' 1>&2; exit; }

[[ $- = *x* ]] || echo 1>&2 'Getting `apt-mark showauto` packages ...'
AUTOS=$(apt-mark showauto "$@")
test "$BACKEND" != 'dialog' || clear
(set -x; apt install $OREC $_G_apt_conf "$@")
test -n "$AUTOS" && apt-mark auto $AUTOS >/dev/null
